version: '{build}'

environment:
  matrix:
    - platform: x64

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 11 x64
  - set CI=true
  - yarn

build: off

on_success:
  - ps: Get-ChildItem .\build\*.exe | % { Push-AppveyorArtifact $_.FullName }

test_script:
  - yarn dist
